version: "3.8"

services:
  db:
    image: postgres:14
    container_name: uber_db
    environment:
      POSTGRES_DB: uberdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s

  app:
    build: .
    container_name: uber_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: uberdb
      DB_USER: postgres
      DB_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
